### ISSUE TITLE
Missing data in Polkadot crypto balances since August 5th

### ISSUE THREAD

**Issue by bradleemorris** [colorfulnotion/substrate-etl#21]
Hello, thanks for the great work you do making these public datasets available! 

I am a user of the datasets for parachain 3369 (crypto_polkadot.balances3369), and noticed that the balances table doesn't seem to be updated since August 5th. It actually looks like this is across the balances tables for all parachains.

**Comment by sourabhniyogi** [comment]
Thanks for the alert!  We're addressing it now and will report back [it appears our cost reduction efforts on the balances GKE deployment were a little too overzealous]

**Comment by sourabhniyogi** [comment]
This is filling in now
```
SELECT TIMESTAMP_TRUNC(ts, DAY), count(*) FROM `substrate-etl.crypto_polkadot.balances3369` WHERE TIMESTAMP_TRUNC(ts, DAY) >= TIMESTAMP("2024-08-01")  group by 1 order by 1 ;
```

<img width="507" alt="image" src="https://github.com/user-attachments/assets/ad68db85-3013-471b-b318-7fb5edeac297">


Thanks again for reporting.

**Comment by bradleemorris** [comment]
That was fast! Thanks

**Comment by aleckamra539** [comment]
Hi! Love this dataset !-- but I noticed two things with this fix.

- The dates between 8/05 and 8/17 aren't being filled in. Is it possible to backfill?
- Because of the missing dates, the balances are off. If someone added tokens during the missing dates, their balance doesn't reflect it. It will assume they are starting with a balance of 0 on 8/17.  A good example of this, is this account: https://mythos.subscan.io/account/0x01e9b3a628a358048d98cae6b97f12748e69b965?tab=balance_history. They added about 11K in MYTH during the gap. But the balance table places them at 2K on the 17th. (They should be around 13K. Which is the 2K + 11K)

**Comment by aleckamra539** [comment]
Hi! it's fine -- it looks like you backfilled everything. Thank you so much for your speedy responses!
